apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana  # This MUST match the folder name in your screenshot
    repo: https://grafana.github.io/helm-charts
    version: 10.4.3
    releaseName: grafana
    namespace: default
#    valuesFile: values.yaml # This file must exist in your 'base' folder
#    chartHome: ../deploy
