apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

#helmCharts:
#- name: grafana
#  valuesFile: values-prod.yaml

commonLabels:
  env: production
  tier: monitoring
